### PR TITLE
libkvmi: add kvmi_alloc_gfn, kvmi_free_gfn, kvmi_create_ept_view, kvmi_destroy_ept_view

### PR DESCRIPTION
**Pull request by thomasdangl**
See related PRs https://github.com/KVM-VMI/qemu/pull/14 and https://github.com/KVM-VMI/kvm/pull/62 for details.

### CODE REVIEW

**Comment by BonusPlay** [comment]
Amazing PR! Is there a plan to add related APIs to libvmi as well, or will these stay in libkvmi?

**Comment by thomasdangl** [comment]
Sure! Our eventual goal is to have a shared API for KVM and Xen for SLAT commands in libvmi.
Some of that work is already here: https://github.com/libvmi/libvmi/pull/1043.
Of course, this still needs some work to be in an acceptable state.
However, we plan to move forward with that PR once we have equal support on the hypervisor side.

Best,
Thomas

**Comment by rageagainsthepc** [comment]
@mdontu-bd Fyi the corresponding PRs have finally been merged.

**Comment by mdontu-bd** [comment]
Thank you!

**Pull request merged**
